### ISSUE TITLE
制御ループの中にサーボONのコマンドが含まれている

### ISSUE THREAD

**Issue by yasuohayashibara** [ryouyasky/b3m_study#1]
制御ループに以下のようにサーボONが入っています．
はじめに１回だけ実行すれば十分で，おそらく頻繁にコマンドを呼び出すと問題が発生すると思います．

https://github.com/ryouyasky/b3m_study/blob/ebef1423f845075b08b401ec27f8b4c75c99b4b0/b3mImu/Src/main.c#L200-L201

**Comment by yasuohayashibara** [comment]
もし試していたら，効果の有無を記載して下さい．

**Comment by ryouyasky** [comment]
サーボONループあり
https://www.youtube.com/watch?v=ctl4G7VdWEU

サーボONループ除外
https://www.youtube.com/watch?v=Wu9nsfRshZs

**Comment by ryouyasky** [comment]
制御ループ外でサーボONを宣言した場合、
サーボに電圧を入れた状態でプログラムを送信すると、エラーが起こりサーボが動かないため、
スイッチが押された時にサーボON命令が入るようにしました。

https://github.com/ryouyasky/b3m_study/blob/a41e5d3c97a185f02cd8734eb107ece0cec28fd2/b3mImu/Src/main.c#L201-L208

**Comment by ryouyasky** [comment]
動画を人力で見ただけではほとんど差は感じられませんでした。
Kinoveaなどを使ったほうがよい？のでしょうか。

**Comment by yasuohayashibara** [comment]
問題かもしれませんが，先ほどIMUのデータを見てIMUのデータの受信に問題があることが分かりました．そちらを解決してから比較をしていただければと思います．

**Comment by ryouyasky** [comment]
こちらに関しては事前に電源を入れたままにしておけばループ外で宣言すれば動作するため問題がないと思われます。
そのためissue閉じさせていただきます。
