### ISSUE TITLE
制御ループ内でのUARTへの出力

### ISSUE THREAD

**Issue by yasuohayashibara** [ryouyasky/b3m_study#2]
UARTへの出力は時間がかかるので，Debugの時以外はコメントアウトした方が良いです．

https://github.com/ryouyasky/b3m_study/blob/ebef1423f845075b08b401ec27f8b4c75c99b4b0/b3mImu/Src/main.c#L242-L243

**Comment by ryouyasky** [comment]
了解しました。
IMUの値を見るとき以外はコメントアウトします。

**Comment by yasuohayashibara** [comment]
コメントアウトしたようですので，issueを閉じます．
