### ISSUE TITLE
サーボモータへのコマンドの送信

### ISSUE THREAD

**Issue by yasuohayashibara** [ryouyasky/b3m_study#3]
サーボモータへのコマンドの送信はまずは１つで試して，ビデオを撮影していただければと思います．

https://github.com/ryouyasky/b3m_study/blob/ebef1423f845075b08b401ec27f8b4c75c99b4b0/b3mImu/Src/main.c#L260

**Comment by yasuohayashibara** [comment]
もしこちらであればその旨記載して下さい．
https://www.youtube.com/watch?v=bKh-zK4X3SY&amp=&feature=share

あと，送信の周期を教えて下さい．
周期の長さとエラーに相関があるおそれがあるため．

**Comment by ryouyasky** [comment]
自身の解釈が間違っているかもしれませんが、UARTの伝送速度はすべて115200bpsにしています。

**Comment by ryouyasky** [comment]
slack上の動画をこちらに添付します


[【動画】 b3mサーボに２つの角度を与えて交互に出力](https://www.youtube.com/watch?v=Bsq2iB7BXM8&feature=share)
[【動画】 b3mサーボでwhileループ内に外付けDelayを入れずに、角度を１００ずつ上昇させる](https://www.youtube.com/watch?v=bKh-zK4X3SY&feature=share)

**Comment by yasuohayashibara** [comment]
Delayを入れていないのであれば，最大速度でコマンドを送信していると思いますので，そちらが問題である懸念が減りました．
再度問題になったときに開くとして，issueを閉じます．
